Repository typedb/typedb-studio, pull requests merged in 2019-02, with the labels that each got.

#5 Wrote README.md
  README.md
Labels: enhancement

#9 Workbase shows a blank screen when Grakn is not running
  src/renderer/components/Login/LoginPage.vue
  src/renderer/components/Visualiser/VisualiserUtils.js
Labels: bug

#33 CI pipeline for Workbase
  .bazelrc
  .circleci/build-workbase-win/README.md
  .circleci/build-workbase-win/build-workbase-win.py
  .circleci/build-workbase-win/instance-setup-template.ps1
  .circleci/config.yml
  BUILD.bazel
  WORKSPACE
  package.json
  test/e2e/QuerySettings.test.js
  test/unit/components/store/actions.test.js
Labels: build
