Repository typedb/typedb-studio, pull requests merged in 2019-08, with the labels that each got.

#181 Update License to 2019
  .circleci/config.yml
  BUILD.bazel
  config/brew/BUILD
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/dependencies.bzl
Labels: refactor

#189 Use yarn in CI
  .circleci/config.yml
  .circleci/windows/README.md
  .circleci/windows/assemble.py
  WORKSPACE
  install-node-electron.sh
  package.json
  tasks/release.js
  yarn.lock
Labels: bug, build

#185 Unifies the logic for producing Canvas nodes and edges
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  dependencies/graknlabs/dependencies.bzl
  package.json
  src/renderer/components/SchemaDesign/SchemaUtils.js
  src/renderer/components/SchemaDesign/store/actions.js
  src/renderer/components/Visualiser/VisualiserGraphBuilder.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
  src/renderer/components/shared/SharedUtils.js
  test/e2e/LoadNeighbours.test.js
  test/e2e/QuerySettings.test.js
  test/helpers/spectron.js
  test/unit/components/ScehmaDesign/store/actions.test.js
  test/unit/components/Visualiser/VisualiserGraphBuilder.test.js
  test/unit/components/Visualiser/store/actions.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
  yarn.lock
Labels: bug, refactor

#193 Includes build, develop and test instructions in the readme
  README.md
Labels: feature

#192 Provides appropriate feedback when running unsupported queries
  src/renderer/components/Visualiser/VisualiserUtils.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: bug

#191 Removes check of instances when un-hasing an attribute from a concept type
  src/renderer/components/SchemaDesign/store/actions.js
Labels: bug

#194 Re-includes the tests that relate to loading relation neighbours
  .circleci/config.yml
  test/e2e/LoadNeighbours.test.js
  test/e2e/QuerySettings.test.js
Labels: refactor
