Repository typedb/typedb-studio, pull requests merged in 2019-05, with the labels that each got.

#139 Shortest path bug
  src/renderer/components/Visualiser/ContextMenu.vue
  src/renderer/components/Visualiser/VisualiserGraphBuilder.js
  test/unit/components/Visualiser/VisualiserGraphBuilder.test.js
Labels: bug

#141 multi-line query with limit bug fix
  src/renderer/components/Visualiser/VisualiserUtils.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: bug

#144 Search keyspaces to connect to
  src/renderer/components/shared/KeyspacesHandler.vue
Labels: feature

#146 Fix CI by synchronizing .bazelrc with @graknlabs_build_tools
  .bazelrc
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build
