Repository typedb/typedb-studio, pull requests merged in 2019-09, with the labels that each got.

#190 Notifies user to wait for running process before clearing the graph or switching keyspaces
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlEditor.vue
  src/renderer/components/shared/KeyspacesHandler.vue
Labels: bug

#187 Add Soroush as the code owner
  .github/CODEOWNERS
Labels: build

#203 Shows labels and arrows on concept type answers and schema
  src/renderer/components/CanvasVisualiser/Events.js
  src/renderer/components/CanvasVisualiser/Visualiser.js
  src/renderer/components/SchemaDesign/Style.js
  src/renderer/components/Visualiser/Style.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/unit/components/shared/CanvasDataBuilder.test.js
Labels: feature

#207 Improves the performance of the CanvasDataBuilder
  src/renderer/components/shared/CanvasDataBuilder.js
Labels: refactor

#208 Fixes the duplicated edges bug
  dependencies/graknlabs/dependencies.bzl
  src/renderer/components/CanvasVisualiser/Facade.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
  src/renderer/components/shared/SharedUtils.js
Labels: bug

#211 Fixes scp failure in .circleci/windows/assemble.py
  .circleci/windows/assemble.py
  package.json
Labels: build

#212 Release 1.2.3
  VERSION
  package.json
  yarn.lock
Labels: build

#213 Uses the latest build-tools
  dependencies/graknlabs/dependencies.bzl
Labels: build

#216 Fixes the bug with missing edge properties
  src/renderer/components/Visualiser/VisualiserGraphBuilder.js
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/unit/components/Visualiser/VisualiserGraphBuilder.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: bug

#217 Fixes a bug with hiding edges on deselecting nodes
  src/renderer/components/CanvasVisualiser/Events.js
Labels: bug

#218 Fixes a bug with explaining inferred concepts
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
Labels: bug

#221 Adapt to latest @graknlabs_bazel_distribution
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build

#222 Use release-validate-deps to ensure that workbase depends on a released version of client-nodejs
  .circleci/config.yml
Labels: build

#223 Fixes a bug with duplicate edges in Schema Designer
  src/renderer/components/shared/CanvasDataBuilder.js
  src/renderer/components/shared/SharedUtils.js
Labels: bug

#220 Release 1.2.4
  dependencies/graknlabs/dependencies.bzl
  package.json
  yarn.lock
Labels: build

#224 Release 1.2.4
  dependencies/graknlabs/dependencies.bzl
Labels: build

#225 Release 1.2.4
  dependencies/graknlabs/dependencies.bzl
Labels: build

#226 Release 1.2.4
  dependencies/graknlabs/dependencies.bzl
Labels: bug
