Repository typedb/typedb-studio, pull requests merged in 2019-10, with the labels that each got.

#229 Migrate assemble-windows to CircleCI Windows
  .circleci/config.yml
  .circleci/windows/README.md
  .circleci/windows/assemble.bat
  .circleci/windows/assemble.py
  .circleci/windows/dependencies.config
  .circleci/windows/prepare.bat
  .circleci/windows/setup-template.ps1
  install-node-electron.sh
Labels: build, refactor

#230 Upgrade CircleCI Orb to version that contains needed tools
  .circleci/config.yml
Labels: bug, build

#231 Fix naming for icons
  assets/icons/256x256.png
  assets/icons/icon.icns
  assets/icons/icon.ico
  package.json
Labels: build, refactor

#232 Fixes a bug with missing properties on nodes produced by double clicking
  src/renderer/components/CanvasVisualiser/Facade.js
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/e2e/helpers/utils.js
  test/helpers/mockedConcepts.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
Labels: bug, refactor

#233 Fixes the bug with loading relation neighbours when "load roleplayers" setting is on
  src/renderer/components/Visualiser/VisualiserUtils.js
Labels: bug

#234 Avoids building edges where its nodes are not visualised
  src/renderer/components/shared/CanvasDataBuilder.js
  test/unit/components/shared/CanvasDataBuilder.test.js
Labels: feature

#235 Makes the right-bar scrollable
  src/renderer/components/SchemaDesign/RightBar.vue
  src/renderer/components/Visualiser/RightBar.vue
Labels: bug

#237 Individual nodes are again draggable after shift + double-clicking on a node.
  src/renderer/components/Visualiser/store/actions.js
Labels: bug

#238 Visualises only the most granular role when loading roleplayers
  src/renderer/components/shared/CanvasDataBuilder.js
Labels: feature

#239 Release Grakn Workbase 1.2.5
  VERSION
  dependencies/graknlabs/dependencies.bzl
Labels: build

#242 Refactor how version is provided to deployment rules
  .circleci/config.yml
  BUILD.bazel
Labels: build, refactor

#243 Provide explanation of inferred concepts where the explanation contains more inferred concepts
  src/renderer/components/SchemaDesign/store/actions.js
  src/renderer/components/Visualiser/RightBar/ConceptInfoTab/RelationsPanel.vue
  src/renderer/components/Visualiser/RightBar/SettingsTab/DisplaySettingsPanel.vue
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlEditor.vue
  src/renderer/components/Visualiser/VisTab.vue
  src/renderer/components/Visualiser/VisualiserContent.vue
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/Visualiser/store/getters.js
  src/renderer/components/Visualiser/store/mutations.js
  src/renderer/components/Visualiser/store/tabState.js
  src/renderer/components/shared/CanvasDataBuilder.js
  src/renderer/components/shared/SharedUtils.js
  src/renderer/components/shared/StoresActions.js
  src/renderer/main.js
  src/renderer/store/actions.js
  src/renderer/store/getters.js
  src/renderer/store/index.js
  test/helpers/mockedConcepts.js
  test/unit/components/ScehmaDesign/SchemaUtils.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
  test/unit/components/Visualiser/performance.test.js
  test/unit/components/Visualiser/store/actions.test.js
  test/unit/components/Visualiser/visTab.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
  yarn.lock
Labels: bug

#244 Auto-loads roleplayers whether or not the relation is subtyped
  src/renderer/components/shared/CanvasDataBuilder.js
  src/renderer/components/shared/SharedUtils.js
  test/e2e/LoadNeighbours.test.js
  test/e2e/QuerySettings.test.js
Labels: bug
