Repository typedb/typedb-studio, pull requests merged in 2019-03, with the labels that each got.

#69 Update workbase to work with grakn 1.5
  README.md
  WORKSPACE
  package.json
  src/renderer/components/Login/LoginPage.vue
  src/renderer/components/SchemaDesign/LeftBar.vue
  src/renderer/components/SchemaDesign/LeftBar/NewRelationPanel.vue
  src/renderer/components/SchemaDesign/RightBar/SettingsTab/DisplaySettingsPanel.vue
  src/renderer/components/SchemaDesign/SchemaHandler.js
  src/renderer/components/SchemaDesign/SchemaUtils.js
  src/renderer/components/SchemaDesign/Style.js
  src/renderer/components/SchemaDesign/store/actions.js
  src/renderer/components/SchemaDesign/store/mutations.js
  src/renderer/components/SchemaDesign/store/state.js
  src/renderer/components/Visualiser/BottomBar/ConsoleUtils.js
  src/renderer/components/Visualiser/RightBar/ConceptInfoTab.vue
  src/renderer/components/Visualiser/RightBar/ConceptInfoTab/RelationsPanel.vue
  src/renderer/components/Visualiser/RightBar/SettingsTab/QuerySettings.js
  src/renderer/components/Visualiser/Style.js
  src/renderer/components/Visualiser/TopBar/TypesContainer.vue
  src/renderer/components/Visualiser/VisualiserCanvasEventsHandler.js
  src/renderer/components/Visualiser/VisualiserFooter.vue
  src/renderer/components/Visualiser/VisualiserGraphBuilder.js
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/Visualiser/store/mutations.js
  src/renderer/components/Visualiser/store/tabState.js
  src/renderer/components/shared/SharedUtils.js
  src/renderer/components/shared/StoresActions.js
  src/renderer/store/actions.js
  test/e2e/LoadNeighbours.test.js
  test/e2e/RelationsPanel.test.js
  test/e2e/TypesPanel.test.js
  test/e2e/VisualiserFooter.test.js
  test/helpers/MockConcepts.js
  test/helpers/basic-genealogy.gql
  test/unit/components/ScehmaDesign/SchemaHandler.test.js
  test/unit/components/ScehmaDesign/store/actions.test.js
  test/unit/components/Visualiser/RightBar/SettingsTab/QuerySettings.test.js
  test/unit/components/Visualiser/VisualiserGraphBuilder.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
  test/unit/components/Visualiser/store/actions.test.js
  test/unit/components/Visualiser/visTab.test.js
Labels: refactor

#72 Update offset and limit of load neighbours and attribute queries
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/Visualiser/store/actions.js
Labels: refactor

#73 Fix unit and integration tests for all platforms
  .circleci/build-workbase-win/build-workbase-win.py
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/dependencies.bzl
  nohup.out
  package.json
  src/renderer/components/Login/LoginPage.vue
  src/renderer/components/SchemaDesign/store/actions.js
  src/renderer/components/Visualiser/VisTab.vue
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/main.js
  src/renderer/store/actions.js
  test/integration/SchemaDesign/SchemaHandler.test.js
  test/integration/store/actions.test.js
  test/unit/components/ScehmaDesign/store/actions.test.js
  test/unit/components/Visualiser/store/actions.test.js
Labels: bug

#76 Fixes in package.json: build DMG for mac, fix repo name
  .circleci/config.yml
  package.json
Labels: build

#78 Limit query bug
  src/renderer/components/Visualiser/VisualiserUtils.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: bug

#80 Conjunction explanation bug
  src/renderer/components/Visualiser/VisualiserGraphBuilder.js
  test/helpers/MockConcepts.js
  test/unit/components/Visualiser/VisualiserGraphBuilder.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: bug

#82 Explanation bug - When explanation answer contains a relationship and its attribute
  src/renderer/components/Visualiser/VisualiserUtils.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: bug

#86 Catch error thrown by grakn.session()
  src/renderer/components/Login/LoginPage.vue
Labels: bug

#91 Filter concepts which were not requested in get clause
  src/renderer/components/Visualiser/VisualiserGraphBuilder.js
Labels: bug

#93 Fix Workbase Windows CI
  .circleci/windows/assemble.py
Labels: bug, build

#94 Add benchmark as transitive dependency
  WORKSPACE
Labels: bug

#95 Fix flaky jest test
  package.json
Labels: feature

#101 remove nohup.out file from repo
  nohup.out
Labels: feature
