Repository typedb/typedb-studio, pull requests merged in 2020-07, with the labels that each got.

#317 Integrate building with BuildBuddy
  .bazelrc
  .bazelversion
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#318 Allows a query that includes an unsupported keyword as a string
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/Visualiser/store/actions.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: type: bug

#322 Fixes automatic extension of user's query with the `limit` and `offset` modifiers
  src/renderer/components/Visualiser/VisualiserUtils.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: type: bug

#323 Updates the Grakn Workbase Logo
  src/renderer/components/Login/LoginPage.vue
  src/renderer/components/SchemaDesign/TopBar.vue
  src/renderer/components/Visualiser/TopBar.vue
  static/img/grakn-workbase-logo.png
  static/img/logo-text.png
  static/img/logo.png
Labels: type: feature

#327 Depend on grakn artifact for tests
  .circleci/config.yml
  BUILD
  WORKSPACE
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/dependencies.bzl
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#332 Excludes already-visualised nodes before updating canvas upon explanation
  src/renderer/components/Visualiser/store/actions.js
Labels: type: bug

#330 Adds Graql syntax highlighting for single quoted strings
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlCodeMirror.js
Labels: type: bug

#328 Improves presentation and logic of attributes displayed on a node's label
  src/renderer/components/shared/CanvasDataBuilder.js
  test/unit/components/shared/CanvasDataBuilder.test.js
Labels: type: bug
