Repository typedb/typedb-studio, pull requests merged in 2020-06, with the labels that each got.

#282 Improves performance of retrieving attributes and role players
  electron-builder.yml
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/e2e/QuerySettings.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: type: refactor

#283 Release 1.2.9
  VERSION
  dependencies/graknlabs/dependencies.bzl
  package.json
Labels: type: build

#291 Brings Grakn 1.8 Support
  dependencies/graknlabs/dependencies.bzl
  package.json
  src/renderer/components/SchemaDesign/LeftBar/NewAttributePanel.vue
  src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/AttributesPanel.vue
  src/renderer/components/SchemaDesign/SchemaHandler.js
  src/renderer/components/SchemaDesign/SchemaUtils.js
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlCodeMirror.js
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/helpers/MockConcepts.js
  test/helpers/gene.gql
  test/helpers/mockedConcepts.js
  test/integration/SchemaDesign/SchemaHandler.test.js
  test/unit/components/ScehmaDesign/SchemaUtils.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
  yarn.lock
Labels: type: feature

#292 Ensures user's query is remained intact upon run
  dependencies/graknlabs/dependencies.bzl
  package.json
  src/renderer/components/SchemaDesign/LeftBar/NewAttributePanel.vue
  src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/AttributesPanel.vue
  src/renderer/components/SchemaDesign/SchemaHandler.js
  src/renderer/components/SchemaDesign/SchemaUtils.js
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlCodeMirror.js
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/helpers/MockConcepts.js
  test/helpers/gene.gql
  test/helpers/mockedConcepts.js
  test/integration/SchemaDesign/SchemaHandler.test.js
  test/unit/components/ScehmaDesign/SchemaUtils.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
  yarn.lock
Labels: type: bug

#289 Ensures closing tabs works reliably and as expected
  src/renderer/components/Visualiser/VisTab.vue
  src/renderer/components/Visualiser/VisualiserContent.vue
  test/e2e/Tabs.test.js
Labels: type: bug

#295 Resolves various bugs in the Schema Designer
  src/renderer/components/SchemaDesign/LeftBar/NewRulePanel.vue
  src/renderer/components/SchemaDesign/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
Labels: type: bug, type: refactor

#296 Notifies the user that no keyspace is selected, upon clicking on the GraqlEditor
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlEditor.vue
Labels: type: bug

#297 Release Workbase 1.2.10
  VERSION
  dependencies/graknlabs/dependencies.bzl
  package.json
  src/renderer/components/SchemaDesign/LeftBar/NewAttributePanel.vue
  src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/AttributesPanel.vue
  src/renderer/components/SchemaDesign/SchemaHandler.js
  src/renderer/components/SchemaDesign/SchemaUtils.js
  src/renderer/components/SchemaDesign/store/actions.js
  src/renderer/components/SchemaDesign/store/mutations.js
  src/renderer/components/SchemaDesign/store/state.js
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlCodeMirror.js
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/helpers/MockConcepts.js
  test/helpers/gene.gql
  test/helpers/mockedConcepts.js
  test/integration/SchemaDesign/SchemaHandler.test.js
  test/unit/components/ScehmaDesign/SchemaUtils.test.js
  test/unit/components/ScehmaDesign/store/actions.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
Labels: type: build

#298 Supports Grakn Core 1.8
  VERSION
  dependencies/graknlabs/dependencies.bzl
  package.json
  src/renderer/components/SchemaDesign/LeftBar/NewAttributePanel.vue
  src/renderer/components/SchemaDesign/RightBar/ConceptInfoTab/AttributesPanel.vue
  src/renderer/components/SchemaDesign/SchemaHandler.js
  src/renderer/components/SchemaDesign/SchemaUtils.js
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlCodeMirror.js
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/helpers/MockConcepts.js
  test/helpers/gene.gql
  test/helpers/mockedConcepts.js
  test/integration/SchemaDesign/SchemaHandler.test.js
  test/unit/components/ScehmaDesign/SchemaUtils.test.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
  test/unit/components/Visualiser/store/actions.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
  yarn.lock
Labels: type: build, type: feature

#300 Fixes a bug where `getRule` gets run on a joint explanation
  VERSION
  package.json
  src/renderer/components/Visualiser/store/actions.js
Labels: type: bug

#309 Retains lines of a multiline query when starring or applying a starred query
  src/renderer/components/Visualiser/TopBar/FavQueries/FavQueriesList.vue
  src/renderer/components/Visualiser/TopBar/GraqlEditor/GraqlEditor.vue
  static/styles/style.css
Labels: type: bug

#306 Displays an error message when running a multiline unsupported query
  src/renderer/components/Visualiser/VisualiserUtils.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
Labels: type: bug

#314 Fix Workbase's CI (assemble-windows-zip is failing)
  .circleci/windows/dependencies.config
  .circleci/windows/prepare.bat
Labels: x: do not merge

#301 Update CI image to Ubuntu 16 and bump build tools
  .circleci/config.yml
  WORKSPACE
  test/e2e/helpers/actions.js
  test/e2e/helpers/canvas.js
Labels: priority: medium, type: build

#304 Fixes loading the neighbours of a relation that plays a role in another relation
  src/renderer/components/Visualiser/VisualiserGraphBuilder.js
  src/renderer/components/Visualiser/VisualiserUtils.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/helpers/mockedConcepts.js
  test/unit/components/Visualiser/VisualiserUtils.test.js
  test/unit/components/Visualiser/store/actions.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
Labels: type: bug

#303 Displays the unassigned relation error in case of a join explanation
  src/renderer/components/Visualiser/VisualiserGraphBuilder.js
  src/renderer/components/Visualiser/store/actions.js
  src/renderer/components/shared/CanvasDataBuilder.js
  test/helpers/mockedConcepts.js
  test/unit/components/Visualiser/store/actions.test.js
  test/unit/components/shared/CanvasDataBuilder.test.js
Labels: type: bug

#312 Set isInferred correctly on a node for both local and remote concepts
  src/renderer/components/Visualiser/ContextMenu.vue
  src/renderer/components/Visualiser/RightBar/ConceptInfoTab/IdentityPanel.vue
  src/renderer/components/shared/CanvasDataBuilder.js
Labels: type: bug

#315 Explains only the given inferred concept
  src/renderer/components/Visualiser/store/actions.js
Labels: type: bug
