Repository typedb/typedb-studio, pull requests merged in 2021-03, with the labels that each got.

#371 Include OS and version in the release asset name
  .bazelignore
  BUILD.bazel
  vue.config.js
Labels: priority: high, type: build, type: refactor

#374 Fix ENTER key destroying visualiser window
  src/components/Login/LoginPage.vue
Labels: priority: blocker, type: bug

#376 Fix enter key causing application turn into black screen
  src/components/Login/LoginPage.vue
Labels: type: bug

#377 Fix the application main window being scrollable
  src/components/MainTemplate/MainTemplate.vue
  src/components/SchemaDesign/RightBar.vue
Labels: type: bug

#378 Fix Homebrew deployment
  BUILD.bazel
Labels: priority: high, type: bug, type: build

#379 Fix cluster database loading
  src/store/actions.js
Labels: type: bug

#383 Do not delete attributes when type doesn't own the attribute
  src/components/SchemaDesign/store/actions.js
Labels: type: bug

#384 Close schema session after switching to visualiser
  src/components/SchemaDesign/TopBar.vue
  src/main.js
  src/store/actions.js
Labels: type: bug

#385 Cleanup Brew deployment job
  .grabl/automation.yml
Labels: type: bug, type: build

#386 Upgrade @graknlabs_dependencies
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: bug, type: build

#387 Upgrade @graknlabs_dependencies
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: bug, type: build
